---
- hosts: all
  become: True
  tasks:
    - name: GIT updated --- now proceeding...
      block:
        - name: Adding user "{{ username }}"  adding with group "{{ ugroup }}"  
          user:
           name: "{{ username }}"
           shell: /bin/bash
           createhome: yes
           update_password: on_create
           password: "{{ my_pass | password_hash('sha512') }}"
           state: present
           groups: "{{ ugroup }}"
           comment: "Created with Ansible"
        - name:   set expire
          shell: chage -E $(( $(date +%s)/3600/24 + {{ expiry }} )) {{ username }}
      when: (git_update == "yes")
