# tasks file for useradd
---
- hosts: all
  become: True
  vars:
          #username: rupin     
     #upass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
     #     ugroup: pubmatic_dev
     expiry: 30
  tasks:
    - set_fact:
        my_pass: "{{ upass }}"

    - name: useradd adding without sudo privileges.
      user:
          name: "{{ username }}"
          shell: /bin/bash
          createhome: yes
          update_password: on_create
          password: "{{ my_pass | password_hash('sha512') }}"
          state: present
          groups: "{{ ugroup }}"
          comment: "Created with Ansible"

    - debug:
          msg: "{{ my_pass }}"


    - name:   set expire
      shell: chage -E $(( $(date +%s)/3600/24 + {{ expiry }} )) {{ username }}
